name: PROD CD

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  run_back_end:
    name: Run backend and deploy on SSH server
    runs-on: ubuntu-latest
    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SSH_IP: ${{ secrets.SSH_IP }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable  # Utilise le canal stable pour obtenir la derni√®re version stable de Flutter

      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Build Flutter APK
        run: |
          cd client
          flutter build apk --release

      - name: Build Flutter web client
        run: |
          cd client
          flutter build web

      - name: Deploy code to server
        run: |
          rsync -avz --exclude='.git' -e "sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no" . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP }}:/${{ secrets.SSH_USERNAME }}/FlashEvent/

      - name: Connect to server and deploy backend
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP }} "
            cd ~/FlashEvent/ &&
            cp client/build/app/outputs/flutter-apk/app-release.apk ~/FlashEvent/apk/ &&
            cp -r client/build/web/* ~/FlashEvent/web/" &&
            docker-compose build --no-cache &&
            docker-compose up -d &&
