name: Go CI

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Augmentez la limite de temps Ã  20 minutes

    strategy:
      matrix:
        go-version: ['1.20', '1.21.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: |
          echo "Running go mod tidy"
          go mod tidy
        working-directory: ./backend

      - name: List files
        run: ls -al
        working-directory: ./backend

      - name: Run tests
        run: |
          echo "Running tests"
          go test -v -timeout 10m ./test/...
        working-directory: ./backend
